apiVersion: v1
kind: Namespace
metadata:
  name: recursing-aryabhata
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: recursing-aryabhata
spec:
  project: default
  source:
    repoURL: https://github.com/sam-andaluri/saas-tenant-recursing-aryabhata.git
    targetRevision: HEAD
    path: tier
  destination:
    server: https://kubernetes.default.svc
    namespace: recursing-aryabhata
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true